name: reuniclus_leju
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^3.0.6
  english_words: ^4.0.0
  provider: ^6.0.0
  graphql_flutter: ^5.1.0
  http: ^0.13.5
  rflutter_alert: ^2.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "diddycon"
  ios: true
  image_path: "diddycon.png"